#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

static uint16_t read_u16_le(const unsigned char *p) {
    return (uint16_t)p[0] | (uint16_t)p[1] << 8;
}

static uint32_t read_u32_le(const unsigned char *p) {
    return (uint32_t)p[0] | (uint32_t)p[1] << 8 | (uint32_t)p[2] << 16 | (uint32_t)p[3] << 24;
}

static void print_usage(const char *prog) {
    fprintf(stderr, "Usage: %s <input.bmp|input.ico> [output.c]\n", prog);
    fprintf(stderr, "If output.c is omitted, the C array is written to stdout.\n");
}

static void write_array(FILE *out, const unsigned char *data, size_t len, const char *name) {
    fprintf(out, "const unsigned char %s[] = {\n", name);
    for (size_t i = 0; i < len; ++i) {
        if ((i & 15) == 0) {
            fprintf(out, "    ");
        }
        fprintf(out, "0x%02X", data[i]);
        if (i + 1 < len) {
            fprintf(out, ", ");
        }
        if ((i & 15) == 15 || i + 1 == len) {
            fprintf(out, "\n");
        }
    }
    fprintf(out, "};\n\n");
    fprintf(out, "const unsigned int %s_len = %zu;\n\n", name, len);
}

int main(int argc, char *argv[]) {
    const char *prog = argc > 0 ? argv[0] : "IMG2CARRAY.exe";
    if (argc < 2 || argc > 3) {
        print_usage(prog);
        return 1;
    }

    const char *inputPath = argv[1];
    const char *outputPath = argc == 3 ? argv[2] : NULL;

    FILE *in = fopen(inputPath, "rb");
    if (!in) {
        fprintf(stderr, "Unable to open input file: %s\n", inputPath);
        return 2;
    }

    if (fseek(in, 0, SEEK_END) != 0) {
        fclose(in);
        fprintf(stderr, "Unable to seek input file.\n");
        return 3;
    }
    long fileSize = ftell(in);
    if (fileSize < 0) {
        fclose(in);
        fprintf(stderr, "Unable to determine input file size.\n");
        return 4;
    }
    rewind(in);

    unsigned char *buffer = (unsigned char *)malloc((size_t)fileSize);
    if (!buffer) {
        fclose(in);
        fprintf(stderr, "Out of memory.\n");
        return 5;
    }

    if (fread(buffer, 1, fileSize, in) != (size_t)fileSize) {
        free(buffer);
        fclose(in);
        fprintf(stderr, "Unable to read input file.\n");
        return 6;
    }
    fclose(in);

    unsigned char *imageData = NULL;
    size_t imageSize = 0;
    const char *arrayName = "image_data";

    if (fileSize >= 2 && buffer[0] == 'B' && buffer[1] == 'M') {
        if (fileSize < 54) {
            fprintf(stderr, "Input file is too small to be a valid BMP.\n");
            free(buffer);
            return 7;
        }

        uint32_t offset = read_u32_le(buffer + 10);
        uint32_t imageLen = read_u32_le(buffer + 34);
        if (offset >= (uint32_t)fileSize) {
            fprintf(stderr, "BMP pixel data offset is outside the file.\n");
            free(buffer);
            return 8;
        }
        if (imageLen == 0 || offset + imageLen > (uint32_t)fileSize) {
            imageLen = (uint32_t)fileSize - offset;
        }
        imageData = buffer + offset;
        imageSize = imageLen;
        fprintf(stderr, "Input detected as BMP; data offset=%u, data length=%zu bytes.\n", offset, imageSize);
    } else if (fileSize >= 6 && buffer[0] == 0 && buffer[1] == 0 && buffer[2] == 1 && buffer[3] == 0) {
        uint16_t count = read_u16_le(buffer + 4);
        if (count == 0) {
            fprintf(stderr, "ICO file contains no image entries.\n");
            free(buffer);
            return 9;
        }
        if ((size_t)6 + count * 16 > (size_t)fileSize) {
            fprintf(stderr, "ICO header is malformed or truncated.\n");
            free(buffer);
            return 10;
        }

        if (count == 1) {
            uint32_t entryOffset = read_u32_le(buffer + 12);
            uint32_t entrySize = read_u32_le(buffer + 8);
            if (entryOffset >= (uint32_t)fileSize || entryOffset + entrySize > (uint32_t)fileSize) {
                fprintf(stderr, "ICO image entry is outside file bounds.\n");
                free(buffer);
                return 11;
            }
            imageData = buffer + entryOffset;
            imageSize = entrySize;
            fprintf(stderr, "Input detected as ICO with 1 image; data offset=%u, data length=%zu bytes.\n", entryOffset, imageSize);
        } else {
            fprintf(stderr, "Input detected as ICO with %u images; emitting all image blocks separately.\n", count);
            FILE *out = outputPath ? fopen(outputPath, "w") : stdout;
            if (!out) {
                fprintf(stderr, "Unable to open output file: %s\n", outputPath);
                free(buffer);
                return 12;
            }
            fprintf(out, "/* Generated by IMG2CARRAY.exe from ICO containing %u images */\n\n", count);
            for (uint16_t idx = 0; idx < count; ++idx) {
                const unsigned char *entry = buffer + 6 + idx * 16;
                uint32_t entrySize = read_u32_le(entry + 8);
                uint32_t entryOffset = read_u32_le(entry + 12);
                if (entryOffset >= (uint32_t)fileSize || entryOffset + entrySize > (uint32_t)fileSize) {
                    fprintf(stderr, "ICO image entry %u is outside file bounds.\n", idx);
                    if (out != stdout) fclose(out);
                    free(buffer);
                    return 13;
                }
                char name[32];
                snprintf(name, sizeof(name), "icon_image_%u", (unsigned)idx);
                write_array(out, buffer + entryOffset, entrySize, name);
            }
            if (out != stdout) fclose(out);
            free(buffer);
            return 0;
        }
    } else {
        fprintf(stderr, "Unsupported file format. Only BMP and ICO are supported.\n");
        free(buffer);
        return 14;
    }

    FILE *out = outputPath ? fopen(outputPath, "w") : stdout;
    if (!out) {
        fprintf(stderr, "Unable to open output file: %s\n", outputPath);
        free(buffer);
        return 15;
    }
    fprintf(out, "/* Generated by IMG2CARRAY.exe from %s */\n\n", inputPath);
    write_array(out, imageData, imageSize, arrayName);

    if (out != stdout) fclose(out);
    free(buffer);
    return 0;
}
